config/routes.rb
Rails.application.routes.draw do

  get '/add_to_book/:id', to: 'spells#add_to_book', as: 'add_to_book'
  get '/add_spell/:id', to: 'books#add_spell', as: 'add_spell'

  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :spells
  resources :books
  resources :spell_books, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :name, presence: true, uniqueness: { case_sensitive: false, message: "Name cannot be the same as an existing book. Case insensitive"}

  has_many :spell_books, dependent: :destroy
  has_many :spells, through: :spell_books

  def self.order_by field
    if field == 'name'
      return Book.order(:name)
    elsif field == 'spell_count'
      count_arr = []
      books = Book.all
      books.each do |book|
        count_arr.append(book.spells.count)
      end
      return Book.order(:count_arr)
    else
      return Book.order(:name)
    end
  end


end

app/models/spell.rb
class Spell < ApplicationRecord
  has_many :spell_books, dependent: :destroy
  has_many :books, through: :spells

  LEVEL = [0, 1, 2, 3, 4, 5, 6 ,7 ,8 ,9]
  SCHOOL_OPTIONS = ['Conjuration', 'Necromancy', 'Evocation', 'Abjuration', 'Transmutation', 'Divination', 'Enchantment', 'Illusion']
  CLASS_OPTIONS = ['Bard', 'Cleric', 'Druid', 'Paladin', 'Ranger', 'Sorcerer', 'Warlock', 'Wizard']
  validates :name, presence: true, uniqueness: { case_sensitive: false, message: "Name cannot be the same as an existing spell. Case insensitive"}
  validates :school, presence: true, inclusion: { in: SCHOOL_OPTIONS }
  validates_presence_of :classes, message: 'A spell must have one or more classes'
  validates_inclusion_of :classes, in: CLASS_OPTIONS
  validates :concentration, inclusion: [true, false]
  validates_length_of :description, maximum: 4096
  validates :level, numericality: {only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 9, message: 'must be between 0 & 9'}

  # validates_numericality_of :level, greater_than_or_equal_to: 0, less_than_or_equal_to: 9, message: 'must be between 0 & 9'
end

app/models/spell_book.rb
class SpellBook < ApplicationRecord
  belongs_to :spell
  belongs_to :book

  validates :spell, uniqueness: { scope: :book, message: "is already added to the book" }

  def spell_count(id)
    book = SpellBook.where({book_id: id})
    book
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  def index
    @books = Book.order_by params[:order_by]
  end

  def create
    @book = Book.new(book_params)

    if @book.save
      flash[:success] = "Successfully created #{@book.name}"
      redirect_to books_path
    else
      render :new
    end
  end

  def new
    @book = Book.new
  end

  def show
  end

  def update
    @book = Book.find params[:id]
    if @book.update(book_params)
      flash[:success] = "Successfully updated #{@book.name}"
      redirect_to books_path
    else
      render :edit
    end
  end

  def destroy
    @book.destroy
    flash[:success] = "Successfully deleted #{@book.name}"
    redirect_to books_path
  end

  def add_spell
    @spell = Spell.all
    @book = Book.find params[:id]
    @spell_book = SpellBook.new
  end

  private
  def set_book
    @book = Book.find params[:id]
  end

  def book_params
    params.require(:book).permit(:name)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/spell_books_controller.rb
class SpellBooksController < ApplicationController
  def create
    @spell_book = SpellBook.new(spell_book_params)
    if @spell_book.save
      flash[:success] = "Successfully added #{@spell_book.spell.name} to #{@spell_book.book.name}"
    else
      flash[:error] = @spell_book.errors.full_messages.join(", ")
    end
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @spell_book = SpellBook.find_by(spell_id: params[:id])
    @spell_book.destroy
    flash[:success] = "Successfully deleted #{@spell_book.spell.name}"
    redirect_to @spell_book.book
  end

  private
  def spell_book_params
    params.require(:spell_book).permit(:book_id, :spell_id, :spell_name)
  end
end

app/controllers/spells_controller.rb
class SpellsController < ApplicationController
  before_action :set_spell, only: [:show, :edit, :update, :destroy, :choose_book, :add_to_book]
  def index
    if !params[:spell]
      spells = Spell.all
      @spell = Spell.new(level: nil, concentration: nil)
    else
      if params[:concentration]
        spells = Spell.where(concentration: query_params[:concentration])
      else
        query_params[:concentration] = nil
      end
      if query_params[:level]
        spells ||= spells.or(Spell.where(level: query_params[:level]))
      else
        query_params[:level] = nil
      end
      spells ||= spells.or(Spell.where(school: query_params[:schools])) if params[:school]
      spells ||= spells.or(Spell.where(classes: query_params[:classes])) if params[:classes]
      @spell = Spell.new(query_params)
    end
    @spells = spells.order('level ASC')
  end

  def show
  end

  def create
    @spell = Spell.new(spell_params)
    if @spell.save
      flash[:success] = "Successfully created #{@spell.name}"
      redirect_to spells_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @spell.update(spell_params)
      flash[:success] = "Successfully Edited #{@spell.name}"
      redirect_to spells_path
    else
      render :edit
    end
  end

  def new
    @spell = Spell.new
  end

  def destroy
    @spell.destroy
    flash[:success] = "Successfully deleted #{@spell.name}"
    redirect_to spells_path
  end

  def add_to_book
    @spell = Spell.find params[:id]
    @books = Book.all
    @spell_book = SpellBook.new
  end

  private
  def spell_params
    params.require(:spell).permit(:name, :level, :school, :concentration, :description, classes: [])
  end

  def query_params
    params.require(:spell).permit(level: [], school: [], concentration: [], classes: [])
  end

  def set_spell
    @spell = Spell.find params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/books/_form.html.erb
<%= form_for book do |form| %>
  <% if book.errors.any? %>
    <ul>
    <% book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
    </ul>
  <% end %>
  <div>
  <%= form.label :name %>
  <%= form.text_field :name %>
  </div>
  <%= form.submit %>
<% end %>

app/views/books/add_spell.html.erb
<h1>Add Spell to <%= @book.name%></h1>
<div>
  <span class="left"><%= link_to "Back to " + @book.name, book_path(@book)%></span>
  <span class="right"><%= link_to "Home", root_path %></span>
</div>
<br>
<br>
<table>
  <thead>
    <tr>
      <th>Spell Name</th>
      <th>Add to Book</th>
    </tr>
  </thead>
  <tbody>
    <% @spell.each do |spell| %>
      <tr>
        <td><%= link_to spell.name, spell_path(spell) %></td>
        <% if @book.spells.find_by(id: spell.id) %>
        <td> Already in book </td>
        <% else %>
          <%= form_for @spell_book do |form| %>
            <% if @spell_book.errors.any? %>
              <ul>
              <% @spell_book.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            <% end %>
            <%= form.hidden_field :book_id, value: @book.id %>
            <%= form.hidden_field :spell_id, value: spell.id %>
            <td>
              <%= form.submit "Add to Book" %>
            </td>
          </tr>
        <% end %>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/books/index.html.erb
<h1>All Books</h1>
<div>
  <span class="left"><%= link_to "Create New", new_book_path %></span>
  <span class="right"><%= link_to "Home", root_path %></span>
</div>
<br>
<br>
<br>
<br>

<table>
  <thead>
    <tr>
      <th><%= link_to "Spell Count", books_path(order_by: "spell_count") %></th>
      <th><%= link_to "Name", books_path(order_by: "name") %></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.spells.count %></td>
        <td><%= link_to book.name, book_path(book) %></td>
        <td><%= button_to "Delete Book", book, method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/new.html.erb
<h1>Create New</h1>

<%= link_to "All Books", books_path%>
<%= link_to "Home", root_path%>

<%= render 'form', book: @book %>

app/views/books/show.html.erb
<h1> View <%= @book.name %></h1>
<div>
  <span class="left"><%= link_to "All Books", books_path %></span>
  <span class="right"><%= link_to "Home", root_path %></span>
</div>
<br>
<br>
<div>
  <table style="border: 1px solid black">
    <thead>
      <tr>
      <th>SpellName</th>
      <th>Remove from Book</th>
      </tr>
    </thead>
    <tbody>
      <% @book.spells.each do |spell| %>
      <tr>
        <td><%= link_to spell.name, spell_path(spell) %></td>
        <td><%= button_to "Remove Spell", spell_book_path(spell), method: :delete%></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= link_to "Add Spell",  add_spell_path%>

app/views/home/index.html.erb
<h1> Home</h1>

<div><%= link_to "All Spells", spells_path %></div>
<div><%= link_to "All SpellBooks", books_path %></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Spellmanager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash.any? %>
      <% flash.each do |type, msg| %>
        <div>
        <%= msg %>
        </div>
      <% end %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/spell_books/new.html.erb
<h1>Add <%= @spell_name  %> to Book</h2>
<div>
  <span class="left"><%= link_to "All Spells", spells_path %></span>
  <span class="right"><%= link_to "Home", root_path %></span>
</div>
<br>
<br>
<h2>Select Book:</h2>
<%= form_for @spell_book do |form| %>
  <% if @spell_book.errors.any? %>
    <ul>
    <% @spell_book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  <% end %>
  <%= form.hidden_field :spell_id, value: @spell %>
  <%= form.select :book_id, @books.collect { |book| [ book.name, book.id] } %>
  <%= form.submit "Submit" %>
<% end %>

app/views/spells/_form.html.erb
<%= form_for spell do |form| %>
  <% if spell.errors.any? %>
    <ul>
    <% spell.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  <% end %>

  <div>
    <%= form.label :level %>
    <%= form.select :level, Spell::LEVEL, prompt: 'Select Level'%>
  </div>
  <br>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name%>
  </div>
    <br>
  <div>
  <%= form.label :school %>
  <%= form.select :school, Spell::SCHOOL_OPTIONS, prompt: "Select a School" %>
  </div>
    <br>
    <div>
    <%= form.radio_button :concentration, false %> No<br />
    <%= form.radio_button :concentration, true %> Yes<br />
    </div>
    <br>
    <div>
    <%= form.label :classes %>
    <% Spell::CLASS_OPTIONS.each do |c| %>
      <%= form.check_box :classes, { multiple: true }, c, false %>
      <%= c %>
    <% end %>
    </div>
    <br>
    <div>
    <%= form.label :description %>
    <%= form.text_area :description %>
    </div>
    <br>
  <%= form.submit %>
<% end %>

app/views/spells/add_to_book.html.erb
<h1>Add <%= @spell.name  %> to Book</h2>
<div>
  <span class="left"><%= link_to "All Spells", spells_path %></span>
  <span class="right"><%= link_to "Home", root_path %></span>
</div>
<br>
<br>
<h2>Select Book:</h2>
<%= form_for @spell_book do |form| %>
  <% if @spell_book.errors.any? %>
    <ul>
    <% @spell_book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  <% end %>
  <%= form.hidden_field :spell_id, value: @spell.id %>
  <%= form.select :book_id, @books.collect { |book| [ book.name, book.id] } %>
  <%= form.submit "Submit" %>
<% end %>

app/views/spells/edit.html.erb
<h1>Edit <%= @spell.name%></h1>

<div>
  <span class="left"><%= link_to "All Spells", spells_path %></span>
  <span class="right"><%= link_to "Home", root_path %></span>
</div>
<br>
<br>

<div class="form">
    <%= render 'form', spell: @spell %>
</div>
<br>
<%= link_to "Delete Spell", @spell, method: :delete%>

app/views/spells/index.html.erb
<h1>All Spells</h1>

<div>
  <span class="left"><%= link_to "Create New Spell", new_spell_path %></span>
  <span class="right"><%= link_to "Home", root_path %></span>
</div>
<br>
<br>

<%= form_for @spell, url: spells_path, method: :get do |form| %>
<div class = "row">
  <div class = "column">
    <ul style="list-style-type:none">
      <%= form.label :level %>
      <% Spell::LEVEL.each do |c| %>
        <li><%= form.check_box :level, { multiple: true }, c, false %> <%= c %> </li>
      <% end %>
    </ul>
  </div>

  <div class = "column">
    <ul style="list-style-type:none">
      <%= form.label :school %>
      <% Spell::SCHOOL_OPTIONS.each do |c| %>
        <li><%= form.check_box :school, { multiple: true }, c, false %> <%= c %> </li>
      <% end %>
    </ul>
  </div>

  <div class = "column">
    <ul style="list-style-type:none">
      <%= form.label :classes %>
      <% Spell::CLASS_OPTIONS.each do |c| %>
        <li><%= form.check_box :classes, { multiple: true }, c, false %> <%= c %> </li>
      <% end %>
    </ul>
  </div>
  <div class="column">
    <ul style="list-style-type:none">
      <%= form.label :concentration %>
      <% [["Yes", true], ["No", false]].each do |c| %>
        <li><%= form.check_box :concentration, { multiple: true }, c[1], false %> <%= c[0] %> </li>
      <% end %>
    </ul>
 </div>
</div>
<div class = "button">
  <%= form.submit "Apply Filter" %>
</div>
  <% end %>

<br>
<br>

<table>
  <thead>
    <tr>
      <th>Level</th>
      <th>SpellName</th>
      <th>School</th>
      <th>Classes</th>
      <th>Concentration</th>
      <th>Edit/Add to Book</th>
    </tr>
  </thead>
  <tbody>
    <% @spells.each do |spell| %>
      <tr>
        <td><%= spell.level%></td>
        <td><%= link_to spell.name, spell_path(spell) %></td>
        <td><%= spell.school %></td>
        <td><%= spell.classes %></td>
        <td><%= spell.concentration %> </td>
        <td>
        <div><%= link_to "Edit", edit_spell_path(spell)%></div>
        <div><%= link_to "Add to Book", add_to_book_path(spell) %></div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/spells/new.html.erb
<h1>Create New</h1>
<div>
  <span class="left"><%= link_to "All Spells", spells_path %></span>
  <span class="right"><%= link_to "Home", root_path %></span>
</div>
<br>
<br>
<div class="form">
    <%= render 'form', spell: @spell %>
<div>

app/views/spells/show.html.erb
<h1>View <%= @spell.name%></h1>
<div>
  <span class="left"><%= link_to "All Spells", spells_path %></span>
  <span class="right"><%= link_to "Home", root_path %></span>
</div>
<br>
<br>
<div>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Level</th>
        <th>School</th>
        <th>Classes</th>
        <th>Concentration</th>
        <th>Description</th>
      </tr>
    </thead>
    <tbody>
        <tr>
          <td><%= @spell.name%></td>
          <td><%= @spell.level%></td>
          <td><%= @spell.school%></td>
          <td><%= @spell.classes%></td>
          <td><%= @spell.concentration%></td>
          <td><%= @spell.description%></td>
        </tr>
    </tbody>
  </table>
</div>

<%= link_to "Add "+@spell.name+" to Book", add_to_book_path(@spell) %>